

POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@email.com"
}

###


POST http://localhost:8080/clients
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@email.com"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "client_id": "d1fbcccf-8f82-40ee-8be4-51efb2ca4911"
}

###

POST http://localhost:8080/accounts
Content-Type: application/json

{
    "client_id": "cba580ee-52b6-4942-b0d0-2cc8673c756a"
}

###

POST http://localhost:8080/transactions
Content-Type: application/json

{
    "account_id_from": "e0b13b3c-fb1b-43db-bc4b-a57082b949e6",
    "account_id_to": "ff7da807-0ae6-4077-8294-2d649ec4cca3",
    "amount": 50
}